name: SonarCloud(Stage1)
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    name: SonarCloud(Stage1)
    runs-on: ubuntu-latest
    steps:
      - name: Go To run Sonar
        run: echo "Go To run Sonar"
